# php-fpm supervisor program
[program:php-fpm]
command=/usr/sbin/php-fpm8.4 -F
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/php-fpm.log
stopwaitsecs=3600
